import Head from 'next/head';
import styles from './layout.module.css';
import Link from 'next/link';
import { Brightness6Rounded } from "@material-ui/icons";
import { useState } from 'react';
import Image from 'next/image';
import world from './Miss_World_logo.svg'


const Layout = ({ children, title = 'World Ranks' }) => {

    const [theme, setTheme] = useState('light');
    const sweatchTheme = () => {
        if (theme === 'light') {
            setTheme('dark');
            document.documentElement.setAttribute('data-theme', 'dark');
        }
        else {
            setTheme('light');
            document.documentElement.setAttribute('data-theme', 'light');
        }
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Link href='/'>
                    <div className={styles.logo}>
                        <Image src={world} alt={'world'}></Image>
                        <div className={styles.logo_name}>World Ranking</div>
                    </div>
                </Link>

                <button className={styles.themeSwitcher} onClick={sweatchTheme}>
                    <Brightness6Rounded />
                </button>
            </header>

            <main className={styles.main}>
                {children}
            </main>

            <footer className={styles.footer}>
                Kotlyarovit@gmail.com
            </footer>
        </div>);
};
export default Layout;